# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0041_invoice_reference_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remittance_data_inr',
            old_name='amount',
            new_name='amount_received',
        ),
        migrations.RenameField(
            model_name='remittance_data_inr',
            old_name='bank_charges',
            new_name='charges_any',
        ),
        migrations.RenameField(
            model_name='remittance_data_inr',
            old_name='tax',
            new_name='igst1',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount1',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount10',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount11',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount12',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount13',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount14',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount15',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount2',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount3',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount4',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount5',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount6',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount7',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount8',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='amount9',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_1',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_10',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_2',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_3',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_4',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_5',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_6',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_7',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_8',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='final_9',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_1',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_10',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_2',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_3',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_4',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_5',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_6',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_7',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_8',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='igst_9',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='invoice_no11',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='invoice_no12',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='invoice_no13',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='invoice_no14',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='invoice_no15',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='proj_name',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services1',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services10',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services11',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services12',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services13',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services14',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services15',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services2',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services3',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services4',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services5',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services6',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services7',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services8',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='services9',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_1',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_10',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_2',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_3',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_4',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_5',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_6',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_7',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_8',
        ),
        migrations.RemoveField(
            model_name='remittance_data_inr',
            name='tax_amt_9',
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name1',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name10',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name2',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name3',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name4',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name5',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name6',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name7',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name8',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='client_name9',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='igst_value9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='principle_tds_ded9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt1',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt10',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt3',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt4',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt5',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt6',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt7',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt8',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt9',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='remitt_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='status',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_amount9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='tds_igst_amt9',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='remittance_data_inr',
            name='total_remitt',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no1',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no10',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no3',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no4',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no5',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no6',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no7',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no8',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='invoice_no9',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='remittance_data_inr',
            name='remarks',
            field=models.TextField(max_length=1200, null=True),
        ),
    ]
